############################################################################
# LICENSE (ISC)                                                            #
############################################################################
#                                                                          #
# Copyright (c) 2008, Evan Klitzke <evan@eklitzke.org>                     #
# Copyright (c) 2012, Thomas Harning Jr <harningt@gmail.com>               #
# Copyright (c) 2018 - 2026, Hisham Muhammad                               #
# Copyright (c) 2026 - 2026, LunarModules maintainers                      #
#                                                                          #
# Permission to use, copy, modify, and/or distribute this software for any #
# purpose with or without fee is hereby granted, provided that the above   #
# copyright notice and this permission notice appear in all copies.        #
#                                                                          #
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES #
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF         #
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR  #
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES   #
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN    #
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF  #
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.           #
#                                                                          #
############################################################################

__EMPTY =
DIRSEP = /
OPENARGDELIMITER = "
CLOSEARGDELIMITER = $(OPENARGDELIMITER)

PACKAGE_REQUIRE_NAME = bz2
PACKAGE_NAME = lua-bz2
PACKAGE_VERSION = 0.2.3
PACKAGE_REVISION = 1
PACKAGE_REPOSITORY_URL = https://github.com/lunarmodules/$(PACKAGE_NAME)
PACKAGE_SOURCE_URL = git+$(PACKAGE_REPOSITORY_URL).git
PACKAGE_SOURCE_BRANCH = master
PACKAGE_TAG = $(PACKAGE_VERSION)
PACKAGE_HOMEPAGE_URL = $(PACKAGE_REPOSITORY_URL)
ROCKSPEC_EXT = .rockspec
ROCKSPEC_DIR = rockspecs
ROCKSPEC_TEMPLATE = $(ROCKSPEC_DIR)$(DIRSEP)rockspec.in
DEV_ROCKSPEC_VERSION = dev
DEV_ROCKSPEC_REVISION = 2
DEV_ROCKSPEC = $(ROCKSPEC_DIR)$(DIRSEP)$(PACKAGE_NAME)-$(DEV_ROCKSPEC_VERSION)-$(DEV_ROCKSPEC_REVISION)$(ROCKSPEC_EXT)
VERSIONED_ROCKSPEC = $(ROCKSPEC_DIR)$(DIRSEP)$(PACKAGE_NAME)-$(PACKAGE_VERSION)-$(PACKAGE_REVISION)$(ROCKSPEC_EXT)

LUAROCKS = luarocks
LUAROCKSLINTARGS =
LUAROCKSMAKEARGS =
LUAROCKSPACKARGS =

LUAROCKS_VERSIONED_SRC_ROCK = $(PACKAGE_NAME)-$(PACKAGE_VERSION)-$(PACKAGE_REVISION).src.rock
LUAROCKS_DEV_SRC_ROCK = $(PACKAGE_NAME)-$(DEV_ROCKSPEC_VERSION)-$(DEV_ROCKSPEC_REVISION).src.rock

TOSTDOUT = >

SED = sed
SEDEFLAG = -e

RM = rm
RMFLAG = -f

ECHO = echo

all: create-rockspecs

echo-src-rock:
	@$(ECHO) $(OPENARGDELIMITER)$(LUAROCKS_VERSIONED_SRC_ROCK)$(CLOSEARGDELIMITER)

echo-dev-src-rock:
	@$(ECHO) $(OPENARGDELIMITER)$(LUAROCKS_DEV_SRC_ROCK)$(CLOSEARGDELIMITER)

echo-dev-rockspec:
	@$(ECHO) $(OPENARGDELIMITER)$(DEV_ROCKSPEC)$(CLOSEARGDELIMITER)

echo-rockspec:
	@$(ECHO) $(OPENARGDELIMITER)$(VERSIONED_ROCKSPEC)$(CLOSEARGDELIMITER)

luarocks-install-dev: $(DEV_ROCKSPEC)
	$(OPENARGDELIMITER)$(LUAROCKS)$(CLOSEARGDELIMITER) make $(LUAROCKSMAKEARGS) $(DEV_ROCKSPEC)

luarocks-install: $(VERSIONED_ROCKSPEC)
	$(OPENARGDELIMITER)$(LUAROCKS)$(CLOSEARGDELIMITER) make $(LUAROCKSMAKEARGS) $(VERSIONED_ROCKSPEC)

luarocks-uninstall-dev:
	$(OPENARGDELIMITER)$(LUAROCKS)$(CLOSEARGDELIMITER) remove $(LUAROCKSREMOVEARGS) $(DEV_ROCKSPEC)

luarocks-uninstall:
	$(OPENARGDELIMITER)$(LUAROCKS)$(CLOSEARGDELIMITER) remove $(LUAROCKSREMOVEARGS) $(VERSIONED_ROCKSPEC)

src-rock: $(LUAROCKS_VERSIONED_SRC_ROCK)

dev-src-rock: $(LUAROCKS_DEV_SRC_ROCK)

$(LUAROCKS_VERSIONED_SRC_ROCK): $(VERSIONED_ROCKSPEC)
	$(OPENARGDELIMITER)$(LUAROCKS)$(CLOSEARGDELIMITER) pack $(LUAROCKSPACKARGS) $(VERSIONED_ROCKSPEC)

$(LUAROCKS_DEV_SRC_ROCK): $(DEV_ROCKSPEC)
	$(OPENARGDELIMITER)$(LUAROCKS)$(CLOSEARGDELIMITER) pack $(LUAROCKSPACKARGS) $(DEV_ROCKSPEC)

lint-rockspecs: lint-dev-rockspec lint-rockspec

lint-dev-rockspec: $(DEV_ROCKSPEC)
	$(OPENARGDELIMITER)$(LUAROCKS)$(CLOSEARGDELIMITER) lint $(LUAROCKSLINTARGS) $(DEV_ROCKSPEC)

lint-rockspec: $(VERSIONED_ROCKSPEC)
	$(OPENARGDELIMITER)$(LUAROCKS)$(CLOSEARGDELIMITER) lint $(LUAROCKSLINTARGS) $(VERSIONED_ROCKSPEC)

create-rockspecs: create-dev-rockspec create-rockspec

create-dev-rockspec: $(DEV_ROCKSPEC)

create-rockspec: $(VERSIONED_ROCKSPEC)

$(DEV_ROCKSPEC): $(ROCKSPEC_TEMPLATE)
	$(SED) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_REQUIRE_NAME@|$(PACKAGE_REQUIRE_NAME)|g$(CLOSEARGDELIMITER) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_NAME@|$(PACKAGE_NAME)|g$(CLOSEARGDELIMITER) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_VERSION@|$(DEV_ROCKSPEC_VERSION)|g$(CLOSEARGDELIMITER) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_REVISION@|$(DEV_ROCKSPEC_REVISION)|g$(CLOSEARGDELIMITER) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_REPOSITORY_URL@|$(PACKAGE_REPOSITORY_URL)|g$(CLOSEARGDELIMITER) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_SOURCE_URL@|$(PACKAGE_SOURCE_URL)|g$(CLOSEARGDELIMITER) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_SOURCE_BRANCH@|$(PACKAGE_SOURCE_BRANCH)|g$(CLOSEARGDELIMITER) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_TAG@|$(PACKAGE_TAG)|g$(CLOSEARGDELIMITER) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_HOMEPAGE_URL@|$(PACKAGE_HOMEPAGE_URL)|g$(CLOSEARGDELIMITER) $(ROCKSPEC_TEMPLATE)$(TOSTDOUT) $(DEV_ROCKSPEC)

$(VERSIONED_ROCKSPEC): $(ROCKSPEC_TEMPLATE)
	$(SED) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_REQUIRE_NAME@|$(PACKAGE_REQUIRE_NAME)|g$(CLOSEARGDELIMITER) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_NAME@|$(PACKAGE_NAME)|g$(CLOSEARGDELIMITER) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_VERSION@|$(PACKAGE_VERSION)|g$(CLOSEARGDELIMITER) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_REVISION@|$(PACKAGE_REVISION)|g$(CLOSEARGDELIMITER) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_REPOSITORY_URL@|$(PACKAGE_REPOSITORY_URL)|g$(CLOSEARGDELIMITER) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_SOURCE_URL@|$(PACKAGE_SOURCE_URL)|g$(CLOSEARGDELIMITER) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_SOURCE_BRANCH@|$(PACKAGE_SOURCE_BRANCH)|g$(CLOSEARGDELIMITER) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_TAG@|$(PACKAGE_TAG)|g$(CLOSEARGDELIMITER) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_HOMEPAGE_URL@|$(PACKAGE_HOMEPAGE_URL)|g$(CLOSEARGDELIMITER) $(ROCKSPEC_TEMPLATE)$(TOSTDOUT) $(VERSIONED_ROCKSPEC)

clean-src-rock:
	-$(RM) $(RMFLAG) $(LUAROCKS_VERSIONED_SRC_ROCK)

clean-dev-src-rock:
	-$(RM) $(RMFLAG) $(LUAROCKS_DEV_SRC_ROCK)

clean-src-rocks: clean-src-rock clean-dev-src-rock

clean-rockspecs: clean-dev-rockspec clean-rockspec

clean-dev-rockspec:
	-$(RM) $(RMFLAG) $(DEV_ROCKSPEC)

clean-rockspec:
	-$(RM) $(RMFLAG) $(VERSIONED_ROCKSPEC)

clean: clean-src-rocks clean-rockspecs

